name: Build

env:
  CARGO_TERM_COLOR: always

on:
  push:
    paths:
      - .github/workflows/**.ya?ml
      - src/**
      - xtask/**
      - "**/*.lock"
      - "**/*.toml"
  workflow_dispatch:

jobs:
  build:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        include:
          - name: macOS
            os: macos-latest
            targets: ["x86_64-apple-darwin", "aarch64-apple-darwin"]
          - name: Linux
            os: ubuntu-latest
            targets: ["x86_64-unknown-linux-gnu"]
          - name: Windows
            os: windows-latest
            targets: ["x86_64-pc-windows-msvc"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2.0.0
        with:
          prefix-key: ${{ runner.os }}

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libgl-dev libjack-dev libx11-xcb-dev  libxcb1-dev libxcb-dri2-0-dev libxcb-icccm4-dev libxcursor-dev libxkbcommon-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Install Rust
        shell: bash
        run: |
          rustup toolchain install stable --profile minimal
          for target in $(yq -r '.[]' <<< '${{ matrix.targets }}'); do
            rustup target add $target
          done

      - name: Build
        shell: bash
        run: |
          for target in $(yq -r '.[]' <<< '${{ matrix.targets }}'); do
            mkdir -p ${{ github.workspace }}/target/bundled/$target
            cargo xtask bundle haashimself --release --target="$target"
            mv ${{ github.workspace }}/target/bundled/HaasHimself.* ${{ github.workspace }}/target/bundled/$target
          done

      - name: Get short commit SHA
        id: short-sha
        shell: bash
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Upload artifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          name: ${{ github.event.repository.name  }}-${{ steps.short-sha.outputs.SHORT_SHA }}-${{ matrix.name }}
          path: ${{ github.workspace }}/target/bundled/
